// This file is automatically generated by a pre-build step
package
{
	import resources.*;

	public class ResourceManager
	{
		public static function init():void
		{
			Atlases.init();
			Audio.init();
			Fonts.init();
			Levels.init();
			Particles.init();
			Screens.init();
		}
	}
}