// This file is automatically generated by a pre-build step
package resources
{
	import starling.textures.Texture;
	import starling.textures.TextureAtlas;

	public class Atlases
	{
		[Embed(source="../../assets/Atlases/Elements.png")]
		private static var ElementsPNG:Class;
		public static var ElementsTextures:TextureAtlas;
		[Embed(source="../../assets/Atlases/Elements.xml", mimeType="application/octet-stream")]
		private static var ElementsXML:Class;

		[Embed(source="../../assets/Atlases/Tiles.png")]
		private static var TilesPNG:Class;
		public static var TilesTextures:TextureAtlas;
		[Embed(source="../../assets/Atlases/Tiles.xml", mimeType="application/octet-stream")]
		private static var TilesXML:Class;

		[Embed(source="../../assets/Atlases/UI.png")]
		private static var UIPNG:Class;
		public static var UITextures:TextureAtlas;
		[Embed(source="../../assets/Atlases/UI.xml", mimeType="application/octet-stream")]
		private static var UIXML:Class;

		public static function init():void
		{
			ElementsTextures = new TextureAtlas(Texture.fromBitmap(new ElementsPNG), XML(new ElementsXML()));
			TilesTextures = new TextureAtlas(Texture.fromBitmap(new TilesPNG), XML(new TilesXML()));
			UITextures = new TextureAtlas(Texture.fromBitmap(new UIPNG), XML(new UIXML()));
		}
	}
}