// This file is automatically generated by a pre-build step
package resources
{
	import flash.media.Sound;
	import flash.media.SoundTransform;

	public class Audio
	{
		[Embed(source="../../assets/Audio/Ghost_Pixels_Theme.mp3")]
		private static var Ghost_Pixels_ThemeMP3:Class;
		public static var Ghost_Pixels_Theme:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_bnc_03.mp3")]
		private static var sfx_disc_bnc_03MP3:Class;
		public static var sfx_disc_bnc_03:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_bnc_04.mp3")]
		private static var sfx_disc_bnc_04MP3:Class;
		public static var sfx_disc_bnc_04:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_fly_01.mp3")]
		private static var sfx_disc_fly_01MP3:Class;
		public static var sfx_disc_fly_01:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_fly_02.mp3")]
		private static var sfx_disc_fly_02MP3:Class;
		public static var sfx_disc_fly_02:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_hit_01.mp3")]
		private static var sfx_disc_hit_01MP3:Class;
		public static var sfx_disc_hit_01:Sound;

		[Embed(source="../../assets/Audio/sfx_disc_hit_02.mp3")]
		private static var sfx_disc_hit_02MP3:Class;
		public static var sfx_disc_hit_02:Sound;

		[Embed(source="../../assets/Audio/sfx_en_cat_01.mp3")]
		private static var sfx_en_cat_01MP3:Class;
		public static var sfx_en_cat_01:Sound;

		[Embed(source="../../assets/Audio/sfx_en_cat_03.mp3")]
		private static var sfx_en_cat_03MP3:Class;
		public static var sfx_en_cat_03:Sound;

		[Embed(source="../../assets/Audio/sfx_en_duck_attack_a_02.mp3")]
		private static var sfx_en_duck_attack_a_02MP3:Class;
		public static var sfx_en_duck_attack_a_02:Sound;

		[Embed(source="../../assets/Audio/sfx_en_duck_attack_a_03.mp3")]
		private static var sfx_en_duck_attack_a_03MP3:Class;
		public static var sfx_en_duck_attack_a_03:Sound;

		[Embed(source="../../assets/Audio/sfx_en_duck_attack_b_03.mp3")]
		private static var sfx_en_duck_attack_b_03MP3:Class;
		public static var sfx_en_duck_attack_b_03:Sound;

		[Embed(source="../../assets/Audio/sfx_en_duck_attack_b_05.mp3")]
		private static var sfx_en_duck_attack_b_05MP3:Class;
		public static var sfx_en_duck_attack_b_05:Sound;

		[Embed(source="../../assets/Audio/sfx_en_gummi_bnc_01.mp3")]
		private static var sfx_en_gummi_bnc_01MP3:Class;
		public static var sfx_en_gummi_bnc_01:Sound;

		[Embed(source="../../assets/Audio/sfx_en_gummi_bnc_02.mp3")]
		private static var sfx_en_gummi_bnc_02MP3:Class;
		public static var sfx_en_gummi_bnc_02:Sound;

		[Embed(source="../../assets/Audio/sfx_en_gummi_death_01.mp3")]
		private static var sfx_en_gummi_death_01MP3:Class;
		public static var sfx_en_gummi_death_01:Sound;

		[Embed(source="../../assets/Audio/sfx_en_gummi_death_03.mp3")]
		private static var sfx_en_gummi_death_03MP3:Class;
		public static var sfx_en_gummi_death_03:Sound;

		[Embed(source="../../assets/Audio/sfx_en_teeth_attack_01.mp3")]
		private static var sfx_en_teeth_attack_01MP3:Class;
		public static var sfx_en_teeth_attack_01:Sound;

		[Embed(source="../../assets/Audio/sfx_en_teeth_attack_02.mp3")]
		private static var sfx_en_teeth_attack_02MP3:Class;
		public static var sfx_en_teeth_attack_02:Sound;

		[Embed(source="../../assets/Audio/sfx_en_teeth_idle_02.mp3")]
		private static var sfx_en_teeth_idle_02MP3:Class;
		public static var sfx_en_teeth_idle_02:Sound;

		[Embed(source="../../assets/Audio/sfx_en_teeth_idle_03.mp3")]
		private static var sfx_en_teeth_idle_03MP3:Class;
		public static var sfx_en_teeth_idle_03:Sound;

		[Embed(source="../../assets/Audio/sfx_player_footstep_01.mp3")]
		private static var sfx_player_footstep_01MP3:Class;
		public static var sfx_player_footstep_01:Sound;

		[Embed(source="../../assets/Audio/sfx_player_footstep_02.mp3")]
		private static var sfx_player_footstep_02MP3:Class;
		public static var sfx_player_footstep_02:Sound;

		[Embed(source="../../assets/Audio/Song_Pillow_Theme.mp3")]
		private static var Song_Pillow_ThemeMP3:Class;
		public static var Song_Pillow_Theme:Sound;

		[Embed(source="../../assets/Audio/Song_Title.mp3")]
		private static var Song_TitleMP3:Class;
		public static var Song_Title:Sound;

		[Embed(source="../../assets/Audio/Sting_Death.mp3")]
		private static var Sting_DeathMP3:Class;
		public static var Sting_Death:Sound;

		[Embed(source="../../assets/Audio/Sting_Win.mp3")]
		private static var Sting_WinMP3:Class;
		public static var Sting_Win:Sound;

		public static function init():void
		{
			Ghost_Pixels_Theme = create(Ghost_Pixels_ThemeMP3);
			sfx_disc_bnc_03 = create(sfx_disc_bnc_03MP3);
			sfx_disc_bnc_04 = create(sfx_disc_bnc_04MP3);
			sfx_disc_fly_01 = create(sfx_disc_fly_01MP3);
			sfx_disc_fly_02 = create(sfx_disc_fly_02MP3);
			sfx_disc_hit_01 = create(sfx_disc_hit_01MP3);
			sfx_disc_hit_02 = create(sfx_disc_hit_02MP3);
			sfx_en_cat_01 = create(sfx_en_cat_01MP3);
			sfx_en_cat_03 = create(sfx_en_cat_03MP3);
			sfx_en_duck_attack_a_02 = create(sfx_en_duck_attack_a_02MP3);
			sfx_en_duck_attack_a_03 = create(sfx_en_duck_attack_a_03MP3);
			sfx_en_duck_attack_b_03 = create(sfx_en_duck_attack_b_03MP3);
			sfx_en_duck_attack_b_05 = create(sfx_en_duck_attack_b_05MP3);
			sfx_en_gummi_bnc_01 = create(sfx_en_gummi_bnc_01MP3);
			sfx_en_gummi_bnc_02 = create(sfx_en_gummi_bnc_02MP3);
			sfx_en_gummi_death_01 = create(sfx_en_gummi_death_01MP3);
			sfx_en_gummi_death_03 = create(sfx_en_gummi_death_03MP3);
			sfx_en_teeth_attack_01 = create(sfx_en_teeth_attack_01MP3);
			sfx_en_teeth_attack_02 = create(sfx_en_teeth_attack_02MP3);
			sfx_en_teeth_idle_02 = create(sfx_en_teeth_idle_02MP3);
			sfx_en_teeth_idle_03 = create(sfx_en_teeth_idle_03MP3);
			sfx_player_footstep_01 = create(sfx_player_footstep_01MP3);
			sfx_player_footstep_02 = create(sfx_player_footstep_02MP3);
			Song_Pillow_Theme = create(Song_Pillow_ThemeMP3);
			Song_Title = create(Song_TitleMP3);
			Sting_Death = create(Sting_DeathMP3);
			Sting_Win = create(Sting_WinMP3);
		}

		private static function create(soundClass:Class):Sound
		{
			var sound:Sound = new soundClass();
			sound.play(0, 0, new SoundTransform(0));
			return sound;
		}
	}
}