// This file is automatically generated by a pre-build step
package resources
{
	import starling.text.BitmapFont;
	import starling.text.TextField;
	import starling.textures.Texture;

	public class Fonts
	{
		[Embed(source="../../assets/Fonts/fortress.png")]
		private static var fortressPNG:Class;
		[Embed(source="../../assets/Fonts/fortress.fnt", mimeType="application/octet-stream")]
		private static var fortressFNT:Class;

		public static function init():void
		{
			TextField.registerBitmapFont(new BitmapFont(Texture.fromBitmap(new fortressPNG()), XML(new fortressFNT())), "fortress");
		}
	}
}