// This file is automatically generated by a pre-build step
package resources
{
	public class Levels
	{
		[Embed(source="../../assets/Ogmo/levels/BossRoom_E_01.oel", mimeType="application/octet-stream")]
		public static var BossRoom_E_01:Class;

		[Embed(source="../../assets/Ogmo/levels/BossRoom_N_01.oel", mimeType="application/octet-stream")]
		public static var BossRoom_N_01:Class;

		[Embed(source="../../assets/Ogmo/levels/BossRoom_S_01.oel", mimeType="application/octet-stream")]
		public static var BossRoom_S_01:Class;

		[Embed(source="../../assets/Ogmo/levels/BossRoom_W_01.oel", mimeType="application/octet-stream")]
		public static var BossRoom_W_01:Class;

		[Embed(source="../../assets/Ogmo/levels/PlayerStartRoom.oel", mimeType="application/octet-stream")]
		public static var PlayerStartRoom:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_EW_01.oel", mimeType="application/octet-stream")]
		public static var Room_EW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_E_01.oel", mimeType="application/octet-stream")]
		public static var Room_E_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NEW_01.oel", mimeType="application/octet-stream")]
		public static var Room_NEW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NE_01.oel", mimeType="application/octet-stream")]
		public static var Room_NE_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NSEW_01.oel", mimeType="application/octet-stream")]
		public static var Room_NSEW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NSE_01.oel", mimeType="application/octet-stream")]
		public static var Room_NSE_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NSW_01.oel", mimeType="application/octet-stream")]
		public static var Room_NSW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NS_01.oel", mimeType="application/octet-stream")]
		public static var Room_NS_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_NW_01.oel", mimeType="application/octet-stream")]
		public static var Room_NW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_N_01.oel", mimeType="application/octet-stream")]
		public static var Room_N_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_SEW_01.oel", mimeType="application/octet-stream")]
		public static var Room_SEW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_SE_01.oel", mimeType="application/octet-stream")]
		public static var Room_SE_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_SW_01.oel", mimeType="application/octet-stream")]
		public static var Room_SW_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_S_01.oel", mimeType="application/octet-stream")]
		public static var Room_S_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Room_W_01.oel", mimeType="application/octet-stream")]
		public static var Room_W_01:Class;

		[Embed(source="../../assets/Ogmo/levels/Sandbox.oel", mimeType="application/octet-stream")]
		public static var Sandbox:Class;

		[Embed(source="../../assets/Ogmo/levels/TreasureRoom_E_01.oel", mimeType="application/octet-stream")]
		public static var TreasureRoom_E_01:Class;

		[Embed(source="../../assets/Ogmo/levels/TreasureRoom_N_01.oel", mimeType="application/octet-stream")]
		public static var TreasureRoom_N_01:Class;

		[Embed(source="../../assets/Ogmo/levels/TreasureRoom_S_01.oel", mimeType="application/octet-stream")]
		public static var TreasureRoom_S_01:Class;

		[Embed(source="../../assets/Ogmo/levels/TreasureRoom_W_01.oel", mimeType="application/octet-stream")]
		public static var TreasureRoom_W_01:Class;

		public static function init():void
		{
		}
	}
}