// This file is automatically generated by a pre-build step
package resources
{
	public class Particles
	{
		[Embed(source="../../assets/Particles/beep.pex", mimeType="application/octet-stream")]
		public static var beep:Class;

		[Embed(source="../../assets/Particles/ring.pex", mimeType="application/octet-stream")]
		public static var ring:Class;

		public static function init():void
		{
		}
	}
}